---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volund-operator-controller-manager
  namespace: volund-system
  labels:
    app.kubernetes.io/name: volund-operator
    app.kubernetes.io/component: controller-manager
